name: binder

# needed for graphviz support
channels:
  - asmeurer # osx
  - mutirri # linux

dependencies:
  - pip
  - numpy
  - toolz
  - dill
  - pandas
  - partd
  - blaze
  - graphviz
  - pip:
      - git+https://github.com/blaze/dask.git#egg=dask[complete]
      - git+https://github.com/blaze/castra.git#egg=castra
